default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: podcast_development

test:
  <<: *default
  database: podcast_test

production:
  <<: *default
  database: podcast_production
  username: podcast
  password: <%= ENV["PODCAST_DATABASE_PASSWORD"] %>
